spring.application.name=woodland
server.servlet.context-path=/api/v1
spring.mongodb.uri=mongodb+srv://jacintoreguera_db_user:Eb7mzhsG5erKPj5l@clusterpruebas.kovnpis.mongodb.net/Woodlands?retryWrites=true&w=majority&appName=ClusterPruebas
spring.mongodb.auto-index-creation: true